version: '3.8'
services:
  backend:
    build: ./server
    ports:
      - "4001:4000"
    env_file:
      - ./server/.env
    environment:
      - MONGO_URI=${MONGODB_URL}
      - JWT_SECRET=${JWT_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SENDER_EMAIL=${SENDER_EMAIL}
    depends_on: []

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=https://api.codeclashes.com
    depends_on:
      - backend
